spring:
  application:
    name: spring-outbox

  datasource:
    url: jdbc:postgresql://${DATABASE_POSTGRES_HOSTNAME:localhost}:${DATABASE_POSTGRES_PORT:5432}/${DATABASE_POSTGRES_DB:postgres}
    username: ${DATABASE_POSTGRES_USERNAME:postgres}
    password: ${DATABASE_POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
