spring:
  application:
    name: spring-outbox

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_POSTGRES_HOSTNAME}/postgres
    username: ${DATABASE_POSTGRES_USERNAME}
    password: ${DATABASE_POSTGRES_PASSWORD}
