spring:
  application:
    name: spring-outbox

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/default
    username: myuser
    password: mypassword
